[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
with-kono = ["kono"]
default = ["with-kono"]
std = ["default"]

[dependencies]
service = { version = "0.1.0", path = "../service" }
controller = { version = "0.1.0", path = "../controller" }
kono = { version = "0.1.0", path = "../kono", optional = true, features = ["with-rocksdb"] }
