[package]
name = "global-id-gen-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
url = "2.2.2"
tokio = { version = "1.13.0", features = ["full"] }
serde = {version = "1.0", features = ["derive"] }

interfaces = { path = "../interfaces", features = ["with-rocksdb"] }
